# Author: Tammy Hartline
# Date: 2024-02-25
# Description: Configuration file for Jekyll site
# Purpose: Set theme for portfolio site

# Alembic Configuration

# Site settings
title: "Tammy Hartline's Computer Science Portfolio"
description: >
  Welcome to my Portfolio Home Landing Page!\n\n
  Hello there! I'm Tammy Hartline, a passionate Computer Science enthusiast specializing in Artificial Intelligence, Data Analytics, and STEM Project Management. With a background in STEM Project Management, I bring a unique blend of leadership, business acumen, and analytical skills to the table. Through my e-portfolio, I showcase my mastery of computer science topics, backed by academic, project, and professional experiences. I am also a mother to three amazing daughters, wife to my wonderful husband for 20 years, and have previous expertise in Business Administration, Banking and Finances, and US tax preparation. Join me on this journey of exploration and innovation in the ever-evolving tech landscape!
baseurl: "/Home" # the subpath of the site page, e.g. /blog/
url: "https://tjhartline.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

theme: jekyll-theme-alembic

plugins:
  - jekyll-feed

# Permalinks
permalink: /:categories/:title/ 

# Exclude from processing and display in RSS
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - node_modules
  - vendor
  - _config.dev.yml
  - .git
  - .gitignore

# Jekyll SEO Tag configuration
seo:
  # Add additional configurations for SEO

# Social Media
social:
  - title: GitHub
    url: https://github.com/tjhartline
  - title: LinkedIn
    url: https://www.linkedin.com/in/tammy-hartline-91981266/
  - title: Email
    url: mailto:tammyhartline@gmail.com

# Navigation
main:
  - title: Home
    url: /
  - title: About Me
    url: /about/
  - title: Contact
    url: /contact/
  - title: Resume
    url: /resume/
  - title: Projects
    url: /projects/
  - title: Artifacts
    url: /artifacts/
    children:
      - title: Software Design and Engineering
        url: /sdae/
      - title: Algorithms and Data Structures
        url: /algorithms/
      - title: Databases
        url: /databases/
